print("---Preços do Aluguel Diario+km---")
print("--10km sai por R$92--")
print("--20km sai por R$94--")
print("--30km sai por R$96--")
print("--40km sai por R$98--")
print("--50km sai por R$100--")
nome=input("Qual seu nome: ")
kms=float(input("Quantos kms voce rodou com o carro? "))
dias=int(input("\nQuantos dias voce ficou com ele? "))
total=(dias*90)+(kms*0.20)
print(f"Voce é {nome}")
print(f"Usou o carro por {dias} dia(s).")
print(f"Andou {kms} kms com o carro.")
print(f"Dando o valor total de R${total}")
print(f"Obrigado por escolher nossa Agencia")